services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_ORG_CREATE: "true"

  test-runner:
    build:
      context: .
    depends_on:
      - grafana
    volumes:
      - grafana-data:/var/lib/grafana
      - ./allure-results:/app/allure-results
      - ./allure-report:/app/allure-report
    command: ["/bin/sh", "/app/scripts/run_tests.sh"]

volumes:
  grafana-data:
