[pytest]
addopts = -ra --strict-markers
testpaths = tests
markers =
    PositiveApi: positive api tests
    NegativeApi: negative api tests
    PositiveOrganizations: positive organizations tests
    PositiveDashboardHub: positive dashboard hub tests
    NegativeDashboardHub: negative dashboard hub tests
    sql: sqlite/mysql validation tests
    cache: redis validation tests
    smoke: smoke tests
    regression: regression tests
    perf: performance tests
filterwarnings =
    ignore::DeprecationWarning
